### ISSUE TITLE
ASSIGNMENT 1A

### ISSUE THREAD

**Issue by azmanyasin** [STIA1123-A201/ASSIGNMENT-1#1]
### **INSTRUCTOR**
Assignment 1

**Please modify the following exercise by using your own topic.**

Write a Java class Author with following features:
1.	Instance variables :
o	firstName for the author’s first name of type String.
o	lastName for the author’s last name of type String.

2.	Constructor:
o	public Author (String firstName, String lastName): A constructor with parameters, it creates the Author object by setting the two fields to the passed values.

3.	Instance methods:
o	public void setFirstName (String firstName): Used to set the first name of author.
o	public void setLastName (String lastName): Used to set the last name of author.
o	public double getFirstName(): This method returns the first name of the author.
o	public double getLastName(): This method returns the last name of the author.
o	public String toString(): This method printed out author’s name to the screen

Write a Java class Book with following features:
1.	Instance variables :
o	title for the title of book of type String.
o	author for the author’s name of type String.
o	price for the book price of type double.

2.	Constructor:
o	public Book (String title, Author name, double price): A constructor with parameters, it creates the Author object by setting the the fields to the passed values.

3.	Instance methods:
o	public void setTitle(String title): Used to set the title of book.
o	public void setAuthor(String author): Used to set the name of author of book.
o	public void setPrice(double price): Used to set the price of book.
o	public double getTitle(): This method returns the title of book.
o	public double getAuthor(): This method returns the author’s name of book.
o	public String toString(): This method printed out book’s details to the screen

Write a separate class BookDemo with a main() method creates a Book titled “Developing Java Software” with authors Russel Winderand price 79.75. Prints the Book’s string representation to standard output (using System.out.print

### **SUBMISION**

1. UML
2. CODING
3. REPORT - OUTPUT

**Comment by Fauzanjaludin** [comment]
https://github.com/Fauzanjaludin/Assignment/tree/master/Assignment%201-prog2

**Comment by mfirdaus07** [comment]
https://github.com/mfirdaus07/Assignment1/tree/master/Assignment-1A

**Comment by wolfoaxx** [comment]
https://github.com/wolfoaxx/Assignment1.git

**Comment by gilbranbp** [comment]
https://github.com/gilbranbp/Assignment1A

**Comment by NellisaAina** [comment]
https://github.com/NellisaAina/MakeUp-Project

**Comment by DanialAsyraf** [comment]
https://github.com/DanialAsyraf/Assignment-1

**Comment by AbuLaithEpic** [comment]
https://github.com/AbuLaithEpic/Assignment-1/issues

**Comment by gilbranbp** [comment]
INPUT: https://github.com/gilbranbp/Assignment1A
OUTPUT: https://github.com/gilbranbp/Assignment1A/issues/1

**Comment by Khairinkasmadi** [comment]
https://github.com/Khairinkasmadi/Assignment1.git

**Comment by FitrianiEka2** [comment]
https://github.com/STIA1123-A201/ASSIGNMENT-1/issues/1#issue-771508506

**Comment by FitrianiEka2** [comment]
https://github.com/FitrianiEka2/Exercise1.git

**Comment by waizazri** [comment]
https://github.com/waizazri/Assignment1

**Comment by Khairinkasmadi** [comment]
https://github.com/Khairinkasmadi/Assignment1.git

**Comment by Sasikala0105** [comment]
https://github.com/Sasikala0105/Assignment1a.git
https://github.com/Sasikala0105/Assignment1aoutput/issues/1#issue-771532243

**Comment by Kalmbyy** [comment]
https://gist.github.com/Abiyyu303/99ea8512c1a2f109eb90f124c3c33a71

**Comment by osbert98** [comment]
https://github.com/osbert98/Assignment1/tree/master/Assignment1

**Comment by noufhajifri** [comment]
https://github.com/noufha/assignment1.git

**Comment by fikriferindraa** [comment]
https://github.com/fikriferindraa/Assignment1

**Comment by danielfirdaus** [comment]
https://github.com/danielfirdaus/Assignment1.git

**Comment by ahmadfaris8** [comment]
https://github.com/ahmadfaris8/Assignment-1A.git

**Comment by suhadaibrahim** [comment]
[https://github.com/suhadaibrahim/assignment/tree/master/assignmentSpaAndSalon/src/assignmentspaandsalon](url)

**Comment by sitinurulnadirah** [comment]
https://github.com/STIA1123-A201/ASSIGNMENT-1/issues/2#issue-771533213

**Comment by MSyafiqbHashim98** [comment]
https://github.com/MSyafiqbHashim98/Assignment1.git

**Comment by suhadaibrahim** [comment]
[https://github.com/suhadaibrahim/assignment/tree/master/assignmentSpaAndSalon/src/assignmentspaandsalon](url)

**Comment by suhadaibrahim** [comment]
[https://github.com/suhadaibrahim/assignment](url)

**Comment by fakahantu0202** [comment]
https://github.com/fakahantu0202/Assignment1A

**Comment by MuhdNadzim** [comment]
https://github.com/MuhdNadzim/Assignment1.git

**Comment by suhadaibrahim** [comment]
[https://github.com/suhadaibrahim/assign1/tree/master/assignmentSpaAndSalon/src/assignmentspaandsalon](url)

**Comment by kunorazranblh** [comment]
https://github.com/kunorazranblh/AssignmentPerfume.git

**Comment by geevitha275649** [comment]
https://github.com/geevitha275649/asgn1/issues

**Comment by suhadaibrahim** [comment]
https://github.com/suhadaibrahim/assignment/tree/master/assignmentSpaAndSalon/src/assignmentspaandsalon

**Comment by nurulErina** [comment]
https://github.com/nurulErina/Assignment-1/tree/master

**Comment by hafizhoho** [comment]
https://github.com/hafizhoho/Assignment-1A.git
